version: '3'
services:
  app:
    container_name: insta-app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true